package com.xworkz.jdbc.go;

import com.xworkz.jdbc.dto.HospitalDTO;
import com.xworkz.jdbc.service.HospitalService;
import com.xworkz.jdbc.service.HospitalServiceImpl;

public class HospitalGo {

	public static void main(String[] args) {
		HospitalDTO hos = new HospitalDTO(1, "Aashraya Hospital","kuradagi", "Surgeon", 1954);
		HospitalDTO hos1 = new HospitalDTO(2, "Fortis Hospital","Rajanna nb", "Eye Care", 1955);
		HospitalDTO hos2 = new HospitalDTO(3, "Shamala Hospital","Shamala Devi", "Gynecologist", 1956);
		HospitalDTO hos3 = new HospitalDTO(4, "Jayadeva Hospital","Jaya", "Cardiologist", 1957);
		HospitalDTO hos4 = new HospitalDTO(5, "Narayana Hospital","Rajanna ", "Orthopedic", 1958);
		HospitalDTO hos5 = new HospitalDTO(6, "Patil Hospital","Lakshmi Patil", "Dental", 1959);
		HospitalDTO hos6 = new HospitalDTO(7, "Chintamani Hospital","Madhusudhan", "Neurologist", 1960);
		HospitalDTO hos7 = new HospitalDTO(8, "Malipatil Hospital","Malashri", "Radiologist", 1961);
		HospitalDTO hos8 = new HospitalDTO(9, "Biradar Hospital","Biradar", "ENT specialist ", 1962);
		HospitalDTO hos9 = new HospitalDTO(10, "Allolli Hospital","Girija", "Child Specialist", 1963);
		HospitalDTO hos10 = new HospitalDTO(11, "Nimabannavar Hospital","Birbal", "Surgeon", 1964);
		HospitalDTO hos11 = new HospitalDTO(12, "Joshi Hospital","Guru", "Kidney Specialist ", 1965);
		HospitalDTO hos12 = new HospitalDTO(13, "N B Patil Hospital","Hema", "Fertility", 1966);
		HospitalDTO hos13 = new HospitalDTO(14, "Gurudeva Hospital","Jaggudada", "Chiropractor", 1967);
		HospitalDTO hos14 = new HospitalDTO(15, "Krishna Hospital","Gangadhar", "Dermatoligist", 1968);
		HospitalDTO hos15 = new HospitalDTO(16, "Manipal Hospital","Manoj", "Allergist", 1969);
		HospitalDTO hos16 = new HospitalDTO(17, "Lokapal Hospital","Lokesh", "Anesthesiologist", 1969);
		HospitalDTO hos17 = new HospitalDTO(18, "Fadnavis Hospital","Fadnavis Gokale", "Massage Therapist", 1970);
		HospitalDTO hos18 = new HospitalDTO(19, "Jaypal Hospital","Jagadish", "ophthalmologist", 1971);
		HospitalDTO hos19 = new HospitalDTO(20, "Gopal Hospital","Vidyashree", "pediatrician", 1972);
		HospitalDTO hos20 = new HospitalDTO(21, "Bhopal Hospital","Divya", "podiatrist", 1973);
		HospitalDTO hos21= new HospitalDTO(22, "HDMC Hospital","Prajwal", "oncologist", 1974);
		HospitalDTO hos22= new HospitalDTO(23, "Ghanti Hospital","Raghavendra", "obstetrician", 1975);
		HospitalDTO hos23= new HospitalDTO(24, "Gadagi Hospital","ramu", "ophthalmologist", 1976);
		HospitalDTO hos24= new HospitalDTO(25, "Jitturi Hospital","hema", "ophthalmologist", 1977);
		HospitalDTO hos25= new HospitalDTO(26, "SDM Hospital","sheela", "Anesthesiologist", 1978);
		HospitalDTO hos26= new HospitalDTO(27, "Nepal Hospital","Vanita", "Allergist", 1979);
		HospitalDTO hos27= new HospitalDTO(28, "Rajpal Hospital","Girija", "Anesthesiologist", 1980);
		HospitalDTO hos28= new HospitalDTO(29, "Mandakini Hospital","Giridhar", "podiatrist", 1981);
		HospitalDTO hos29= new HospitalDTO(30, "Muncipal Hospital","Arun", "Allergist", 1982);
		HospitalDTO hos30= new HospitalDTO(31, "Guggari Hospital","Tarun", "Chiropractor", 1983);
		HospitalDTO hos31= new HospitalDTO(32, "Narak Hospital","Fakrudin", "Allergist", 1984);
		HospitalDTO hos32 = new HospitalDTO(33, "Yamloka Hospital","Gokul", "podiatrist", 1985);
		HospitalDTO hos33= new HospitalDTO(34, "Daamini Hospital","gagan", "obstetrician", 1986);
		HospitalDTO hos34= new HospitalDTO(35, "SatyaSai Hospital","Shamla", "podiatrist", 1987);
		HospitalDTO hos35= new HospitalDTO(36, "Fedreral Hospital","Rajanna nb", "Eye Care", 1988);
		HospitalDTO hos36= new HospitalDTO(37, "Niranjan Hospital","Rajanna nb", "Eye Care", 1989);
		HospitalDTO hos37= new HospitalDTO(38, "Chiniwal Hospital","Rajanna nb", "Eye Care", 1990);
		HospitalDTO hos38= new HospitalDTO(39, "Nasrekar Hospital","Rajanna nb", "Eye Care", 1991);
		HospitalDTO hos39= new HospitalDTO(40, "Choori Hospital","Rajanna nb", "Eye Care", 1992);
		HospitalDTO hos40= new HospitalDTO(41, "Nair Hospital","Rajanna nb", "Eye Care", 1993);
		HospitalDTO hos41= new HospitalDTO(42, "Bhuvan Hospital","Rajanna nb", "Eye Care", 1994);
		HospitalDTO hos42= new HospitalDTO(43, "Niveditha Hospital","Rajanna nb", "Eye Care", 1995);
		HospitalDTO hos43 = new HospitalDTO(44, "Dharmastala Hospital","Rajanna nb", "Eye Care", 1996);
		HospitalDTO hos44= new HospitalDTO(45, "AdiChunchangiri Hospital","Rajanna nb", "Eye Care", 1997);
		HospitalDTO hos45= new HospitalDTO(46, "Gangadhar Hospital","Rajanna nb", "Eye Care", 1998);
		HospitalDTO hos46= new HospitalDTO(47, "Giridhar Hospital","Rajanna nb", "Eye Care", 1999);
		HospitalDTO hos47= new HospitalDTO(48, "Revankar Hospital","Rajanna nb", "Eye Care", 2000);
		HospitalDTO hos48= new HospitalDTO(49, "Palankar Hospital","Rajanna nb", "Eye Care", 2001);
		HospitalDTO hos49= new HospitalDTO(50, "Revathi Hospital","Rajanna nb", "Eye Care", 2002);
		HospitalDTO hos50= new HospitalDTO(51, "Rampal Hospital","Rajanna nb", "Eye Care", 2003);
		HospitalDTO hos51= new HospitalDTO(52, "Ambani Hospital","Rajanna nb", "Eye Care", 2004);
		HospitalDTO hos52= new HospitalDTO(53, "Dhirubhai Hospital","Rajanna nb", "Eye Care", 2005);
		HospitalDTO hos53= new HospitalDTO(54, "Siddarth Hospital","Rajanna nb", "Eye Care", 2006);
		HospitalDTO hos54= new HospitalDTO(55, "Jaykar Hospital","Rajanna nb", "Eye Care", 2007);
		HospitalDTO hos55= new HospitalDTO(56, "James Hospital","Rajanna nb", "Eye Care", 2008);
		HospitalDTO hos56= new HospitalDTO(57, "Jayleela Hospital","Rajanna nb", "Eye Care", 2009);
		HospitalDTO hos57= new HospitalDTO(58, "Lalitha Hospital","Rajanna nb", "Eye Care", 2010);
		HospitalDTO hos58= new HospitalDTO(59, "Unnati Hospital","Rajanna nb", "Eye Care", 2011);
		HospitalDTO hos59= new HospitalDTO(60, "Ujwal Hospital","Rajanna nb", "Eye Care", 2012);
		HospitalDTO hos60= new HospitalDTO(61, "Sanmathi Hospital","Rajanna nb", "Eye Care", 2013);
		HospitalDTO hos61= new HospitalDTO(62, "ShreeLeela Hospital","Nagesh", "physical therapist", 2014);
		HospitalDTO hos62= new HospitalDTO(63, "Tirumala Hospital","Abhishek", "radiologist", 2015);
		HospitalDTO hos63= new HospitalDTO(64, "Texas Hospital","Sachin", "oncologist", 2016);
		HospitalDTO hos64= new HospitalDTO(65, "Eretiga Hospital","Deepthismitha", "naturopath", 2017);
		HospitalDTO hos65= new HospitalDTO(66, "Helena Hospital","Sushma", "midwife", 2018);
		HospitalDTO hos66= new HospitalDTO(67, "Helena Hospital","Sushma", "midwife", 2018);
		HospitalDTO hos67= new HospitalDTO(67, "Helena Hospital","Sushma", "midwife", 2018);

//		System.out.println(hos);
//		System.out.println(hos1);
//		System.out.println(hos2);
//		System.out.println(hos3);
//		System.out.println(hos4);
//		System.out.println(hos5);
//		System.out.println(hos6);
//		System.out.println(hos7);
//		System.out.println(hos8);
//		System.out.println(hos9);
//		System.out.println(hos10);
//		System.out.println(hos11);
//		System.out.println(hos12);
//		System.out.println(hos13);
//		System.out.println(hos14);
//		System.out.println(hos15);
//		System.out.println(hos16);
//		System.out.println(hos17);
//		System.out.println(hos19);
//		System.out.println(hos20);
//		System.out.println(hos21);
//		System.out.println(hos22);
//		System.out.println(hos23);
//		System.out.println(hos24);
//		System.out.println(hos25);
//		System.out.println(hos26);
//		System.out.println(hos27);
//		System.out.println(hos28);
//		System.out.println(hos29);
//		System.out.println(hos30);
//		System.out.println(hos31);
//		System.out.println(hos32);
//		System.out.println(hos33);
//		System.out.println(hos34);
//		System.out.println(hos35);
//		System.out.println(hos36);
//		System.out.println(hos37);
//		System.out.println(hos38);
//		System.out.println(hos39);
//		System.out.println(hos40);
//		System.out.println(hos41);
//		System.out.println(hos42);
//		System.out.println(hos43);
//		System.out.println(hos44);
//		System.out.println(hos45);
//		System.out.println(hos46);
//		System.out.println(hos47);
//		System.out.println(hos48);
//		System.out.println(hos49);
//		System.out.println(hos50);
//		System.out.println(hos51);
//		System.out.println(hos52);
//		System.out.println(hos53);
//		System.out.println(hos54);
//		System.out.println(hos55);
//		System.out.println(hos56);
//		System.out.println(hos57);
//		System.out.println(hos58);
//		System.out.println(hos59);
//		System.out.println(hos60);
//		System.out.println(hos61);
//		System.out.println(hos62);
//		System.out.println(hos63);
//		System.out.println(hos64);
//		System.out.println(hos65);
//		System.out.println(hos66);





		HospitalService service = new HospitalServiceImpl();
		service.validateAndSave(hos);
		service.validateAndSave(hos1);
		service.validateAndSave(hos2);
		service.validateAndSave(hos3);
		service.validateAndSave(hos4);
		service.validateAndSave(hos5);
		service.validateAndSave(hos6);
		service.validateAndSave(hos7);
		service.validateAndSave(hos8);
		service.validateAndSave(hos9);
		service.validateAndSave(hos10);
		service.validateAndSave(hos11);
		service.validateAndSave(hos12);
		service.validateAndSave(hos13);
		service.validateAndSave(hos14);
		service.validateAndSave(hos15);
		service.validateAndSave(hos16);
		service.validateAndSave(hos17);
		service.validateAndSave(hos18);
		service.validateAndSave(hos19);
		service.validateAndSave(hos20);
		service.validateAndSave(hos21);
		service.validateAndSave(hos22);
		service.validateAndSave(hos23);
		service.validateAndSave(hos24);
		service.validateAndSave(hos25);
		service.validateAndSave(hos26);
		service.validateAndSave(hos27);
		service.validateAndSave(hos28);
		service.validateAndSave(hos29);
		service.validateAndSave(hos30);
		service.validateAndSave(hos31);
		service.validateAndSave(hos32);
		service.validateAndSave(hos33);
		service.validateAndSave(hos34);
		service.validateAndSave(hos35);
		service.validateAndSave(hos36);
		service.validateAndSave(hos37);
		service.validateAndSave(hos38);
		service.validateAndSave(hos39);
		service.validateAndSave(hos40);
		service.validateAndSave(hos41);
		service.validateAndSave(hos42);
		service.validateAndSave(hos43);
		service.validateAndSave(hos44);
		service.validateAndSave(hos45);
		service.validateAndSave(hos46);
		service.validateAndSave(hos47);
		service.validateAndSave(hos48);
		service.validateAndSave(hos49);
		service.validateAndSave(hos50);
		service.validateAndSave(hos51);
		service.validateAndSave(hos52);
		service.validateAndSave(hos53);
		service.validateAndSave(hos54);
		service.validateAndSave(hos55);
		service.validateAndSave(hos56);
		service.validateAndSave(hos57);
		service.validateAndSave(hos58);
		service.validateAndSave(hos59);
		service.validateAndSave(hos60);
		service.validateAndSave(hos61);
		service.validateAndSave(hos62);
		service.validateAndSave(hos63);
		service.validateAndSave(hos64);
		service.validateAndSave(hos65);
		service.validateAndSave(hos66);
		service.validateAndSave(hos67);

		

	}
}
